version: '3.4'

volumes:
  postgres_data:
      driver: local

networks:
  notification-dev:
    driver: bridge

services:
  notification: 
    image: ${DOCKER_REGISTRY-}notification
    build:
      context: .
      dockerfile: Notification/Dockerfile
    links:
        - "redis"
    ports:
        - 8000:80
        - 8001:443
    networks:
        - notification-dev
  postgres:
    container_name: pg_container
    image: postgres:latest
    restart: always
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: notification
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
        - "5432:5432"
    networks:
        - notification-dev
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "5050:80"
    networks:
        - notification-dev
  redis:
    container_name: redis_container
    image: redis:latest
    networks:
        - notification-dev
